---
apiVersion: kubeteach.geberl.io/v1alpha1
kind: ExerciseSet
metadata:
  name: set
spec:
  taskDefinitions:
    - name: task01
      taskDefinitionSpec:
        taskSpec:
          title: "task01"
          description: "task01 - should be successful"
        taskCondition:
          - apiVersion: v1
            kind: Namespace
            name: "task01"
    - name: task02
      taskDefinitionSpec:
        taskSpec:
          title: "task02"
          description: "task02 - should be active"
        requiredTaskName: "task01"
        taskCondition:
          - apiVersion: v1
            kind: Namespace
            name: "task02"
    - name: task03
      taskDefinitionSpec:
        taskSpec:
          title: "task03"
          description: "task03 - should be pending"
        requiredTaskName: "task02"
        taskCondition:
          - apiVersion: v1
            kind: Namespace
            name: "task03"
---
apiVersion: v1
kind: Namespace
metadata:
  name: task01
spec: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test
subjects:
  - kind: ServiceAccount
    name: kubeteach-controller-manager
    namespace: kubeteach-system
