---
apiVersion: kubeteach.geberl.io/v1alpha1
kind: TaskDefinition
metadata:
  name: task01
spec:
  taskSpec:
    title: "task01"
    description: "task01 - should be successful"
  taskCondition:
    - apiVersion: v1
      kind: Namespace
      name: "task01"
---
apiVersion: kubeteach.geberl.io/v1alpha1
kind: TaskDefinition
metadata:
  name: task02
spec:
  taskSpec:
    title: "task02"
    description: "task02 - should be active"
  requiredTaskName: "task01"
  taskCondition:
    - apiVersion: v1
      kind: Namespace
      name: "task02"
---
apiVersion: kubeteach.geberl.io/v1alpha1
kind: TaskDefinition
metadata:
  name: task03
spec:
  taskSpec:
    title: "task03"
    description: "task03 - should be pending"
  requiredTaskName: "task02"
  taskCondition:
    - apiVersion: v1
      kind: Namespace
      name: "task03"
---
apiVersion: v1
kind: Namespace
metadata:
  name: task01
spec: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kubeteach-system
