# permissions for end users to edit exercisesets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: exerciseset-editor-role
rules:
- apiGroups:
  - kubeteach.geberl.io
  resources:
  - exercisesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeteach.geberl.io
  resources:
  - exercisesets/status
  verbs:
  - get
