# permissions for end users to edit taskdefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: taskdefinition-editor-role
rules:
- apiGroups:
  - kubeteach.geberl.io
  resources:
  - taskdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeteach.geberl.io
  resources:
  - taskdefinitions/status
  verbs:
  - get
