# permissions for end users to view taskdefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: taskdefinition-viewer-role
rules:
- apiGroups:
  - kubeteach.geberl.io
  resources:
  - taskdefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeteach.geberl.io
  resources:
  - taskdefinitions/status
  verbs:
  - get
