apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: colorconf-pod
  name: colorconf-pod
  namespace: kubeteach
spec:
  containers:
  - env:
    - name: COLOR
      valueFrom:
        configMapKeyRef:
          name: colorconf
          key: color
    image: nginx
    name: colorconf-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
