apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: kubeteach-rolebinding
  namespace: kubeteach
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubeteach-pod-role
subjects:
- kind: ServiceAccount
  name: kubeteach-sa
  namespace: kubeteach
