---
apiVersion: kubeteach.geberl.io/v1alpha1
kind: TaskDefinition
metadata:
  name: task1
spec:
  taskSpec:
    title: "Create a Namespace"
    description: "Create a Namespace with the name kubeteach"
  taskConditions:
    - apiVersion: v1
      kind: Namespace
      resourceCondition:
        - field: "metadata.name"
          operator: "eq"
          value: "kubeteach"
---
apiVersion: kubeteach.geberl.io/v1alpha1
kind: TaskDefinition
metadata:
  name: task2
spec:
  taskSpec:
    title: "Create a Pod"
    description: "Create a pod in the default Namespace with the image nginx"
  taskConditions:
    - apiVersion: v1
      kind: Pod
      resourceCondition:
        - field: "metadata.name"
          operator: "eq"
          value: "pod1"
        - field: "metadata.namespace"
          operator: "eq"
          value: "default"
        - field: "spec.containers.0.image"
          operator: "eq"
          value: "nginx"
---
apiVersion: kubeteach.geberl.io/v1alpha1
kind: TaskDefinition
metadata:
  name: task3
spec:
  requiredTaskName: task2
  taskSpec:
    title: "Create a Pod"
    description: "Create a pod in the default Namespace with the image nginx"
  taskConditions:
    - apiVersion: v1
      kind: Pod
      resourceCondition:
        - field: "metadata.name"
          operator: "eq"
          value: "pod2"
        - field: "metadata.namespace"
          operator: "eq"
          value: "default"
        - field: "spec.containers.0.image"
          operator: "eq"
          value: "nginx"
---
apiVersion: kubeteach.geberl.io/v1alpha1
kind: TaskDefinition
metadata:
  name: task4
spec:
  taskSpec:
    title: "Create a Pod"
    description: "Create a pod in the default Namespace with the image nginx"
  taskConditions:
    - apiVersion: v1
      kind: Pod
      resourceCondition:
        - field: "metadata.name"
          operator: "eq"
          value: "pod2"
        - field: "metadata.namespace"
          operator: "eq"
          value: "default"
        - field: "spec.containers.0.image"
          operator: "eq"
          value: "nginx"
---
apiVersion: kubeteach.geberl.io/v1alpha1
kind: TaskDefinition
metadata:
  name: task5
spec:
  taskSpec:
    title: "Delete Namespace"
    description: "Delete Namespace from task1 (kubeteach)"
  requiredTaskName: task1
  taskConditions:
    - apiVersion: v1
      kind: Namespace
      matchAll: true
      resourceCondition:
        - field: "metadata.name"
          operator: "neq"
          value: "kubeteach"