---
apiVersion: kubeteach.geberl.io/v1alpha1
kind: TaskDefinition
metadata:
  name: task1
spec:
  taskSpec:
    title: "Create a Namespace"
    description: "Create a Namespace with the name kubeteach"
  taskConditions:
    - apiVersion: v1
      kind: Namespace
      name: "kubeteach"
      resourceCondition:
        - field: "metadata.name"
          operator: "eq"
          value: "kubeteach"
---
apiVersion: kubeteach.geberl.io/v1alpha1
kind: TaskDefinition
metadata:
  name: task2
spec:
  taskSpec:
    title: "Create a Pod"
    description: "Create a pod in the default Namespace with the image nginx"
  taskConditions:
    - apiVersion: v1
      kind: Pod
      name: "pod1"
      namespace: "default"
      resourceCondition:
        - field: "spec.containers.0.image"
          operator: "eq"
          value: "nginx"
---
apiVersion: kubeteach.geberl.io/v1alpha1
kind: TaskDefinition
metadata:
  name: task3
spec:
  requiredTaskName: task2
  taskSpec:
    title: "Create a Pod"
    description: "Create a pod in the default Namespace with the image nginx"
  taskConditions:
    - apiVersion: v1
      kind: Pod
      name: "pod2"
      namespace: "default"
      resourceCondition:
        - field: "spec.containers.0.image"
          operator: "eq"
          value: "nginx"
---
apiVersion: kubeteach.geberl.io/v1alpha1
kind: TaskDefinition
metadata:
  name: task4
spec:
  taskSpec:
    title: "Create a Pod"
    description: "Create a pod in the default Namespace with the image nginx"
  taskConditions:
    - apiVersion: v1
      kind: Pod
      name: "pod1"
      namespace: "default"
---
apiVersion: kubeteach.geberl.io/v1alpha1
kind: TaskDefinition
metadata:
  name: task5
spec:
  taskSpec:
    title: "Delete Namespace"
    description: "Delete Namespace from task1 (kubeteach)"
  requiredTaskName: task1
  taskConditions:
    - name: "pod1"
      kind: "Namespace"
      apiVersion: "v1"
      namespace: "default"
      resourceCondition:
        - field: "bla"
          operator: "eq"