name: build

on:
  push:
    branches:
      - 'main'
      - 'feature/earthly'
    tags:
      - 'v*'

jobs:
  build:
    environment: build
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate docker metadata
      id: docker_meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/dergeberl/kubeteach,dergeberl/kubeteach
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.REGISTRY }}
    - uses: earthly/actions-setup@v1
      with:
        version: "latest"
    - name: Earthly version
      run: earthly --version
    - name: Run build
      run: earthly --ci +all
