name: tests

on:
  push:
#    branches: [ main ]
#    tags: [ 'v*' ]
#  pull_request:
#    branches: [ main ]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
         go-version: '1.16'
      - name: go-vendor
        run: go mod vendor
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        env:
          GOPRIVATE: github.com
          GO111MODULE: "on"
        with:
          version: v1.29
          args: --modules-download-mode "vendor"
#  test:
##    needs: [ golangci ]
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        go: ['1.11', '1.12', '1.13', '1.14', '1.15']
#    steps:
#      - uses: actions/setup-go@v1
#        with:
#          go-version: ${{ matrix.go }}
#      - uses: actions/checkout@v2
#      - run: go test -v -coverprofile=profile.cov ./...